### ISSUE TITLE
container registry-buddy in cf-api-server and cf-api-worker pods always stop 

### ISSUE THREAD

**Issue by davincizhao** [cloudfoundry/capi-k8s-release#117]
registry-buddy in cf-api-server and cf-api-worker pods always stop  and start

sometime is works, sometime in crash status. restart  again and again.

**Comment by davincizhao** [comment]
Server is listening at 127.0.0.1:8080...
2021/08/15 04:19:24 Server is attempting to shut down...
2021/08/15 04:19:27 Server stopped
![image](https://user-images.githubusercontent.com/22903476/129467115-8afcd9ac-1555-4ce9-9f7d-b5a8de8e63ba.png)

**Comment by davincizhao** [comment]
![image](https://user-images.githubusercontent.com/22903476/129467158-42b9d6ed-ebc1-4fd6-9b5c-24b0ed8c4f10.png)

**Comment by nicko170** [comment]
@davincizhao  I was seeing the same thing. I have fixed it by introducing a longer timeout. This does mean you will have to edit the cf-for-k8s repo too. 

in `cf-for-k8s/vendir.yml`  - update where the capi-k8s-release comes from
```
directories:
- path: config/capi/_ytt_lib/capi-k8s-release
  contents:
  - path: .
    git:
      url: https://github.com/nicko170/capi-k8s-release
      ref: 2e9979e78ae6f2a640db8a6132b0c56fe8676119
```

run `vendir sync` to pull the changes
Regenerate your rendered file
`ytt -f config -f ${TMP_DIR}/cf-values.yml > ${TMP_DIR}/cf-for-k8s-rendered.yml`

And finally, kapps deploy will work.
kapp deploy -a cf -f ${TMP_DIR}/cf-for-k8s-rendered.yml  -y
