### ISSUE TITLE
Missing configuration values

### ISSUE THREAD

**Issue by kramerul** [cloudfoundry/capi-k8s-release#7]
We tried to use this helm chart together with quarks.

We noticed that for this use case several configuration values are missing:

* `uaa.internal_url` in `ccng-configmap.yaml`

```
internal_url: {{ .Values.uaa.internal_url | default "http://uaa.{{ .Release.Namespace }}.svc.cluster.local:8080" }}
```

* `blobstore.signature_version`  in `ccng-configmap.yaml`

```
aws_signature_version: {{ .Values.blobstore.signature_version | default "2" | quote }}
```

* `blobstore.region`  in `ccng-configmap.yaml`

```
region: {{ .Values.blobstore.region | quote }}
```

* `nameserver` in `api_server_deployment.yaml` (this is only required to resolve BOSH DNS names like `uaa.service.cf.internal`. In a kubernetes native environment, this is not really required)

```
      {{- if .Values.nameserver }}
      dnsConfig:
        nameservers:
        - {{ .Values.nameserver }}
        options:
        - name: ndots
          value: "5"
        searches:
        - {{ .Release.Namespace }}.svc.cluster.local
        - svc.cluster.local
        - cluster.local
        - service.cf.internal
      dnsPolicy: None
      {{- end }}
```
